[Service]
Host = "172.17.0.1"
Port = 49990
ConnectRetries = 3
HealthCheck = "/api/v1/ping"
Labels = []
OpenMsg = "Camera Discovery Started"
ReadMaxLimit = 256
Timeout = 5000

[Registry]
Type = "consul"
Host = "localhost"
Port = 8500
CheckInterval = "15s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  name = "edgex-core-data"
  Protocol = "http"
  Host = "localhost"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  name = "edgex-core-metadata"
  Protocol = "http"
  Host = "localhost"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "localhost"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmd2 = "HandleReadCommands"
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"
  SendReadingsOnChanged = true

[Writable]
LogLevel = "INFO"

[Logging]
EnableRemote = false
File = "./device-camera-go-service.log"
RemoteURL = ''

# Pre-defined Devices - useful for tests or to populate static camera addresses (i.e., known at deployment time) to expedite their discovery
[[DeviceList]]
  Name = "MockAxisCamera001"
  Profile = "camera-profile-axis"
  Description = "Initial Axis camera configured on service startup"
  Labels = [ "camera", "axis" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
    Address = "axis001"
    Port = "49990"

[[DeviceList]]
  Name = "MockAxisCamera002"
  Profile = "camera-profile-axis"
  Description = "Initial Axis camera configured on service startup"
  Labels = [ "camera", "axis" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
    Address = "axis002"
    Port = "49990"
