[Service]
Host = "127.0.0.1"
Port = 49990
ConnectRetries = 3
HealthCheck = "/api/v1/ping"
Labels = []
OpenMsg = "Camera device service started"
ReadMaxLimit = 256
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "localhost"
Port = 8500
CheckInterval = "15s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Host = "localhost"
  Port = 48080
  Timeout = 50000
  Protocol = "HTTP"

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Host = "localhost"
  Port = 48081
  Timeout = 50000
  Protocol = "HTTP"

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"
  SendReadingsOnChanged = true

[Logging]
RemoteURL = ''
File = "./device-camera-go-service.log"

# Pre-defined Devices
[[DeviceList]]
  Name = "Camera001"
  Profile = "camera-bosch"
  Description = "My test Bosch camera"
  Location = "foo"
  [DeviceList.Protocols]
    [DeviceList.Protocols.HTTP]
      Address = "192.168.2.105"
#  Name = "Camera001"
#  Profile = "camera-axis"
#  Description = "My test Axis camera"
#  Location = "foo"
#  [DeviceList.Protocols]
#    [DeviceList.Protocols.HTTP]
#      Address = "192.168.2.163"